### ISSUE TITLE
accepts nested schema.many attributes for?

### ISSUE THREAD

**Issue by activestylus** [bdurand/json_record#2]
Since embedded has_many models are vanilla ruby classes, how can I set up a multi-model form given that accepts_nested_attributes is no longer an option? Here's what I'm working with:

BEFORE

```
class Template < ActiveRecord::Base

  has_many :inputs
  accepts_nested_attributes_for :inputs, :allow_destroy => true, :reject_if => proc { |obj| obj.blank? }

end

class Input < ActiveRecord::Base

  belongs_to :template

end
```

AFTER

```
class Template < ActiveRecord::Base

  serialize_to_json(:data) do |schema|
    schema.many :inputs, Input
  end

end

class Input
  include JsonRecord::EmbeddedDocument
  schema.key :name
  schema.key :type
  schema.key :help_text
  schema.key :filter
end
```

Am I reaching too far beyond the scope of this gem?

**Comment by bdurand** [comment]
This should work just fine. You can set the attributes on the embedded documents by just using an array of hashes:

``` ruby
t = Template.new(:inputs => [{:name => "one", :type => "thing"}, {:name => "two", :type => "other"}])
t.inputs.first.name # "one"
t.inputs.last.name # "two"
```

**Comment by activestylus** [comment]
Awesome! It took a bit of fiddling, and it feels a bit kludgy - but here's how it's working:

``` ruby
= form_for @template do |f|
  = label_tag :name
  = f.text_field :name

  - @template.inputs.each_with_index do |input, i|
    .field
      = label_tag "Name"
      = text_field_tag "template[inputs][#{i}][name]", (input.name if input.name)
```

I do miss the more concise syntax of fields_for, but the following attempts both failed

(1)

``` ruby
= fields_for :inputs do |i|
    i.text_field :name
```

That just gave me a name attribute of "inputs[name]", which is worthless

(2)

``` ruby
= fields_for @template.inputs do |i|
    i.text_field :name
```

As expected that bombed out on me with: "undefined method `model_name' for JsonRecord::EmbeddedDocumentArray:Class"

You can view the stack trace here: http://pastie.textmate.org/2184053

It's really a small thing and I don't expect you to bust your hump on it, but you certainly could win a nice userbase with a little polish here and there.

_Last issue:_

Another thing I'm having trouble wrapping my head around is the deletion of nested inputs. I know I can pop the last one out and save the model, but how do I get specific? Is there some sort of input I can set up like accepts_nested _delete so I can flag certain items to be nuked when the parent is saved?

**Comment by activestylus** [comment]
Tinkering a bit more I found the solution.

``` ruby
# parent model
class Template < ActiveRecord::Base

  serialize_to_json(:data) do |schema|
    schema.many :inputs, Input
  end

  def before_validation
    inputs.each {|input| inputs.delete(input) if input._delete}
  end

end


# embedded model
class Input
  include JsonRecord::EmbeddedDocument  

  schema.key :name
  schema.key :_delete # <= mark as unwanted

end

# view
- @template.inputs.each_with_index do |input, i|

  = label_tag "Name"
  = text_field_tag "template[inputs][#{i}][name]", (input.name if input.name)

  = check_box_tag "template[inputs][#{i}][_delete]"
  = label_tag "Delete"
```

Frikkin sweet!

I suppose it would be kind of cool to have a configurable default :_delete schema.key for all embedded models in your project, or some callable option within the schema.many method. It would also be pretty rad if the fields_for helpers JustWorked™. But those are just icing on an otherwise delicious cake. The basics are working fine here and that's what counts.
